export type BibleBook = {
    name: string;       // Full name of the book (e.g., "창세기")
    abbr: string;       // Abbreviation of the book (e.g., "창")
    chapters: number;   // Number of chapters in the book
    verses: number;     // Number of verses in the book (or a more complex structure if needed)
}

export type BibleBooks = {
    [key: string]: BibleBook; // Keys are strings, and values are of type BibleBook
}

export const bibleBooks: BibleBooks = {
    'gen': {'name': '창세기', 'abbr': '창', 'chapters': 50, 'verses': 26},
    'exo': {'name': '출애굽기', 'abbr': '출', 'chapters': 40, 'verses': 38},
    'lev': {'name': '레위기', 'abbr': '레', 'chapters': 27, 'verses': 34},
    'num': {'name': '민수기', 'abbr': '민', 'chapters': 36, 'verses': 13},
    'deu': {'name': '신명기', 'abbr': '신', 'chapters': 34, 'verses': 12},
    'josh': {'name': '여호수아', 'abbr': '수', 'chapters': 24, 'verses': 33},
    'jdgs': {'name': '사사기', 'abbr': '삿', 'chapters': 21, 'verses': 25},
    'ruth': {'name': '룻기', 'abbr': '룻', 'chapters': 4, 'verses': 22},
    '1sm': {'name': '사무엘상', 'abbr': '삼상', 'chapters': 31, 'verses': 13},
    '2sm': {'name': '사무엘하', 'abbr': '삼하', 'chapters': 24, 'verses': 25},
    '1ki': {'name': '열왕기상', 'abbr': '왕상', 'chapters': 22, 'verses': 53},
    '2ki': {'name': '열왕기하', 'abbr': '왕하', 'chapters': 25, 'verses': 30},
    '1chr': {'name': '역대상', 'abbr': '대상', 'chapters': 29, 'verses': 36},
    '2chr': {'name': '역대하', 'abbr': '대하', 'chapters': 36, 'verses': 35},
    'ezra': {'name': '에스라', 'abbr': '스', 'chapters': 10, 'verses': 44},
    'neh': {'name': '느헤미야', 'abbr': '느', 'chapters': 13, 'verses': 31},
    'est': {'name': '에스더', 'abbr': '에', 'chapters': 10, 'verses': 3},
    'job': {'name': '욥기', 'abbr': '용', 'chapters': 42, 'verses': 17},
    'psa': {'name': '시편', 'abbr': '시', 'chapters': 150, 'verses': 6},
    'prv': {'name': '잠언', 'abbr': '잠', 'chapters': 31, 'verses': 9},
    'eccl': {'name': '전도서', 'abbr': '전', 'chapters': 12, 'verses': 14},
    'ssol': {'name': '아가', 'abbr': '아', 'chapters': 8, 'verses': 12},
    'isa': {'name': '이사야', 'abbr': '사', 'chapters': 66, 'verses': 24},
    'jer': {'name': '예레미야', 'abbr': '렘', 'chapters': 52, 'verses': 34},
    'lam': {'name': '예레미야 애가', 'abbr': '애', 'chapters': 5, 'verses': 22},
    'eze': {'name': '에스겔', 'abbr': '겔', 'chapters': 48, 'verses': 13},
    'dan': {'name': '다니엘', 'abbr': '단', 'chapters': 12, 'verses': 14},
    'hos': {'name': '호세아', 'abbr': '호', 'chapters': 14, 'verses': 10},
    'joel': {'name': '요엘', 'abbr': '욜', 'chapters': 3, 'verses': 21},
    'amos': {'name': '아모스', 'abbr': '암', 'chapters': 9, 'verses': 15},
    'obad': {'name': '오바댜', 'abbr': '옵', 'chapters': 1, 'verses': 21},
    'jonah': {'name': '요나', 'abbr': '욘', 'chapters': 4, 'verses': 11},
    'mic': {'name': '미가', 'abbr': '미', 'chapters': 7, 'verses': 20},
    'nahum': {'name': '나훔', 'abbr': '나', 'chapters': 3, 'verses': 19},
    'hab': {'name': '하박국', 'abbr': '합', 'chapters': 3, 'verses': 19},
    'zep': {'name': '스바냐', 'abbr': '습', 'chapters': 3, 'verses': 18},
    'hag': {'name': '학개', 'abbr': '학', 'chapters': 2, 'verses': 23},
    'zec': {'name': '스가랴', 'abbr': '슥', 'chapters': 14, 'verses': 21},
    'mal': {'name': '말라기', 'abbr': '말', 'chapters': 4, 'verses': 6},
    'mat': {'name': '마태복음', 'abbr': '마', 'chapters': 28, 'verses': 20},
    'mark': {'name': '마가복음', 'abbr': '막', 'chapters': 16, 'verses': 20},
    'luke': {'name': '누가복음', 'abbr': '누', 'chapters': 24, 'verses': 53},
    'john': {'name': '요한복음', 'abbr': '요', 'chapters': 21, 'verses': 25},
    'acts': {'name': '사도행전', 'abbr': '사', 'chapters': 28, 'verses': 31},
    'rom': {'name': '로마서', 'abbr': '로', 'chapters': 16, 'verses': 27},
    '1cor': {'name': '고린도전서', 'abbr': '고전', 'chapters': 16, 'verses': 24},
    '2cor': {'name': '고린도후서', 'abbr': '고후', 'chapters': 13, 'verses': 14},
    'gal': {'name': '갈라디아서', 'abbr': '갈', 'chapters': 6, 'verses': 18},
    'eph': {'name': '에베소서', 'abbr': '엡', 'chapters': 6, 'verses': 24},
    'phi': {'name': '빌립보서', 'abbr': '빌', 'chapters': 4, 'verses': 23},
    'col': {'name': '골로새서', 'abbr': '골', 'chapters': 4, 'verses': 18},
    '1th': {'name': '데살로니가전서', 'abbr': '살전', 'chapters': 5, 'verses': 28},
    '2th': {'name': '데살로니가후서', 'abbr': '살후', 'chapters': 3, 'verses': 18},
    '1tim': {'name': '디모데전서', 'abbr': '딤전', 'chapters': 6, 'verses': 21},
    '2tim': {'name': '디모데후서', 'abbr': '딤후', 'chapters': 4, 'verses': 22},
    'titus': {'name': '디도서', 'abbr': '딛', 'chapters': 3, 'verses': 15},
    'phmn': {'name': '빌레몬서', 'abbr': '몬', 'chapters': 1, 'verses': 25},
    'heb': {'name': '히브리서', 'abbr': '히', 'chapters': 13, 'verses': 25},
    'jas': {'name': '야고보서', 'abbr': '약', 'chapters': 5, 'verses': 20},
    '1pet': {'name': '베드로전서', 'abbr': '벧전', 'chapters': 5, 'verses': 14},
    '2pet': {'name': '베드로후서', 'abbr': '벧후', 'chapters': 3, 'verses': 18},
    '1jn': {'name': '요한1서', 'abbr': '요일', 'chapters': 5, 'verses': 21},
    '2jn': {'name': '요한2서', 'abbr': '요이', 'chapters': 1, 'verses': 13},
    '3jn': {'name': '요한3서', 'abbr': '요삼', 'chapters': 1, 'verses': 14},
    'jude': {'name': '유다서', 'abbr': '유', 'chapters': 1, 'verses': 25},
    'rev': {'name': '요한계시록', 'abbr': '계', 'chapters': 22, 'verses': 21},
}
export const books: string[] = Object.keys(bibleBooks)